name: task_repository
description: Dart package which manages the authentication domain.
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter_secure_storage: ^4.2.1
  jwt_decoder: ^2.0.1
  http: ^0.13.4
